
include fortran/basemakefile

COMPILER := gfortran --free-form
LIB_FLAGS := -lblas -llapack
COMP_DEBUG_FLAGS := -Wall -Wextra -pedantic
EXEC_DEBUG_FLAGS := -fbacktrace -fbounds-check -ffpe-trap=zero,overflow -fmax-errors=1
OPTIMIZE_FLAGS :=

